### ISSUE TITLE
server error when attempting to log in

### ISSUE THREAD

**Issue by iopq** [cr4yfish/learn-better#1]
![Screenshot_20241103-165917](https://github.com/user-attachments/assets/6fe32741-7d21-47f0-9cac-5a1793d3c392)

**Comment by cr4yfish** [comment]
Thanks so much for the bug report! I'll fix it ASAP

**Comment by cr4yfish** [comment]
Alright I think I located and fixed the issue.

The error happened after sign up, login and then choosing a first course, right?

I totally forgot to add the chosen course as a "current course" in the user settings, which is then "null" in the database. That's not expected in the Level scroller tho, which then errors out.

The bug should be fixed in the new version going up.

**Comment by cr4yfish** [comment]
ok had some build issues fixed.

The issue itself is fixed and bugged user settings should fix themselves now when visiting the Homepage.

Let me know if the issue persists or a new one popped up. Thanks again!
